# Generated by Django 5.1.2 on 2024-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принят к работе'), ('in_progress', 'Находится в работе'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
