# Generated by Django 5.1.2 on 2024-10-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_date_order_delivery_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_place',
        ),
    ]
