# Generated by Django 5.1.2 on 2024-10-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
